import type { Metadata } from "next";

import { Navbar } from "../components/navbar/Navbar";
import ThemeProvider from "../components/theme/ThemeProvider";
import "./globals.css";
import "./fonts.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVBAR_CATEGORIES = [
  { label: "Home", route: "/" },
  { label: "Forum", route: "/forum" },
  { label: "Contact", route: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `;(function(){try{var s=window.sessionStorage.getItem('theme');var t=s?s:(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.body.setAttribute('data-theme', t); }catch(e){} })()`,
          }}
        />
      </head>
      <body className="antialiased ">
        <ThemeProvider>
          <Navbar categories={NAVBAR_CATEGORIES} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
