import type { Metadata } from "next";

import { Navbar } from "../components/navbar/Navbar";
import ThemeProvider from "../components/theme/ThemeProvider";
import "./globals.css";
import "./fonts.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVBAR_CATEGORIES = [
  { label: "About", route: "/about" },
  { label: "Forum", route: "/forum" },
  { label: "Contact", route: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `;(function(){
              try {
                var s = window.localStorage.getItem('theme');
                var t = s ? s : (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                document.documentElement.setAttribute('data-theme', t);
              } catch(e){}
            })();`,
          }}
        />
      </head>
      <body className="antialiased">
        <ThemeProvider>
          <Navbar categories={NAVBAR_CATEGORIES} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
